@echo off
echo Starting the HealthEcho Game application...

echo Starting Flask backend server...
start cmd /c "cd ..\healthview-echogame-nextjs\backend && python API_server.py"

echo Starting frontend development server...
npm run dev

echo Shutting down servers...
